/**
 * ProjectFilesActivityLog — Drone Phase 1 PR7c
 *
 * Live audit feed of project_folder_events for one project.
 *  - Initial fetch via api.entities.ProjectFolderEvent.list()
 *  - Realtime: subscribes to ProjectFolderEvent inserts via api shim,
 *    invalidates query on relevant project's events
 *  - Filters: event_type, folder_kind, actor_type, free-text search on file_name
 *  - Pagination: "Load more" raises page size in 50-event increments
 *
 * Mounted from ProjectFilesTab.jsx in the placeholder slot.
 *
 * Backend dependencies (already in place):
 *   - project_folder_events table (migration 221)
 *   - Realtime publication on project_folder_events (migration 226)
 *   - api.entities.ProjectFolderEvent (auto-generated by api shim's
 *     PascalCase → snake_case → plural mapping)
 */

import { useEffect, useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "@/api/supabaseClient";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Activity,
  ServerCog,
  Webhook,
  User as UserIcon,
  RefreshCw,
  Loader2,
  Search,
} from "lucide-react";
import { formatDistanceToNow, format } from "date-fns";
import { cn } from "@/lib/utils";

// ── Mirrors ALL_FOLDER_KINDS from ProjectFilesTab ────────────────────────
const ALL_FOLDER_KINDS = [
  "raw_photos",
  "raw_drones",
  "raw_videos",
  "enrichment_drone_renders_proposed",
  "enrichment_drone_renders_adjusted",
  "enrichment_orthomosaics",
  "enrichment_sfm_meshes",
  "final_delivery_drones",
  "audit",
];

const FOLDER_LABELS = {
  raw_photos: "Photos",
  raw_drones: "Drones",
  raw_videos: "Videos",
  enrichment_drone_renders_proposed: "Renders (Proposed)",
  enrichment_drone_renders_adjusted: "Renders (Adjusted)",
  enrichment_orthomosaics: "Orthomosaics",
  enrichment_sfm_meshes: "SfM Meshes",
  final_delivery_drones: "Final Drone Deliveries",
  audit: "Audit",
};

// ── Event types we currently emit (see _shared/projectFolders.ts + dropbox-webhook) ──
const ALL_EVENT_TYPES = [
  "folders_created",
  "file_added",
  "file_removed",
  "file_moved",
  "link_generated",
  "link_revoked",
  "override_applied",
];

const EVENT_LABELS = {
  folders_created: "Folders provisioned",
  file_added: "File added",
  file_removed: "File removed",
  file_moved: "File moved",
  link_generated: "Shared link generated",
  link_revoked: "Shared link revoked",
  override_applied: "Folder override applied",
};

const EVENT_TONES = {
  folders_created: "default",
  file_added: "default",
  file_removed: "destructive",
  file_moved: "secondary",
  link_generated: "secondary",
  link_revoked: "destructive",
  override_applied: "outline",
};

const ALL_ACTOR_TYPES = ["system", "webhook", "user"];

const ACTOR_LABELS = {
  system: "System",
  webhook: "Dropbox webhook",
  user: "User",
};

const ACTOR_ICONS = {
  system: ServerCog,
  webhook: Webhook,
  user: UserIcon,
};

const PAGE_INCREMENT = 50;

function formatBytes(n) {
  if (typeof n !== "number" || !isFinite(n) || n <= 0) return null;
  const k = 1024;
  const sizes = ["B", "KB", "MB", "GB", "TB"];
  const i = Math.min(Math.floor(Math.log(n) / Math.log(k)), sizes.length - 1);
  return `${(n / Math.pow(k, i)).toFixed(i === 0 ? 0 : 1)} ${sizes[i]}`;
}

export default function ProjectFilesActivityLog({ projectId }) {
  const queryClient = useQueryClient();
  const [eventTypeFilter, setEventTypeFilter] = useState("all");
  const [folderKindFilter, setFolderKindFilter] = useState("all");
  const [actorTypeFilter, setActorTypeFilter] = useState("all");
  const [search, setSearch] = useState("");
  const [pageSize, setPageSize] = useState(PAGE_INCREMENT);

  // Initial fetch + manual refresh button.
  // We over-fetch by `pageSize` server-side then filter client-side; this
  // keeps the realtime add path simple and is bounded by pageSize so it
  // can't blow up the UI even on chatty projects.
  const queryKey = ["project_folder_events", projectId, pageSize];
  const { data: events, isLoading, isFetching, refetch } = useQuery({
    queryKey,
    queryFn: () =>
      api.entities.ProjectFolderEvent.list(
        { project_id: projectId },
        { orderBy: "-created_at", limit: pageSize }
      ),
    staleTime: 5_000,
    enabled: Boolean(projectId),
  });

  // Realtime: invalidate on inserts for this project. Use api.entities.subscribe()
  // pattern (matches ChatPanel / ConcurrentEditDetector). The subscription is
  // global to the table; we filter by project_id in the callback.
  useEffect(() => {
    if (!projectId) return;
    let active = true;

    const unsubscribe = api.entities.ProjectFolderEvent.subscribe((evt) => {
      if (!active) return;
      if (evt.type !== "create") return;
      if (evt.data?.project_id !== projectId) return;
      // Trigger a refetch (debounced via staleTime/react-query batching).
      queryClient.invalidateQueries({ queryKey: ["project_folder_events", projectId] });
    });

    return () => {
      active = false;
      try {
        if (typeof unsubscribe === "function") unsubscribe();
      } catch (e) {
        console.warn("[ProjectFilesActivityLog] unsubscribe failed:", e);
      }
    };
  }, [projectId, queryClient]);

  const filtered = useMemo(() => {
    if (!Array.isArray(events)) return [];
    return events.filter((e) => {
      if (eventTypeFilter !== "all" && e.event_type !== eventTypeFilter) return false;
      if (folderKindFilter !== "all" && e.folder_kind !== folderKindFilter) return false;
      if (actorTypeFilter !== "all" && e.actor_type !== actorTypeFilter) return false;
      if (search.trim()) {
        const s = search.trim().toLowerCase();
        const haystack = [
          e.file_name,
          e.event_type,
          e.folder_kind,
          e.actor_type,
          typeof e.metadata === "object" ? JSON.stringify(e.metadata) : null,
        ]
          .filter(Boolean)
          .join(" ")
          .toLowerCase();
        if (!haystack.includes(s)) return false;
      }
      return true;
    });
  }, [events, eventTypeFilter, folderKindFilter, actorTypeFilter, search]);

  const hasFilters =
    eventTypeFilter !== "all" ||
    folderKindFilter !== "all" ||
    actorTypeFilter !== "all" ||
    search.trim() !== "";

  const totalLoaded = events?.length ?? 0;
  const reachedPageEnd = totalLoaded < pageSize; // server returned fewer rows than asked → no more

  return (
    <Card className="mt-6">
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between gap-2">
          <CardTitle className="text-base flex items-center gap-2">
            <Activity className="h-4 w-4 text-muted-foreground" />
            Activity log
            {isFetching && !isLoading && (
              <Loader2 className="h-3 w-3 animate-spin text-muted-foreground" />
            )}
          </CardTitle>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => refetch()}
            disabled={isFetching}
            className="h-7 px-2 text-xs"
            title="Refresh"
          >
            <RefreshCw className={cn("h-3 w-3", isFetching && "animate-spin")} />
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-3">
        {/* Filter bar */}
        <div className="flex flex-wrap gap-2 items-center">
          <div className="relative flex-1 min-w-[180px]">
            <Search className="absolute left-2 top-2.5 h-3.5 w-3.5 text-muted-foreground" />
            <Input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search file name, event, folder…"
              className="pl-7 h-9 text-xs"
            />
          </div>
          <Select value={eventTypeFilter} onValueChange={setEventTypeFilter}>
            <SelectTrigger className="h-9 w-[180px] text-xs">
              <SelectValue placeholder="Event type" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All events</SelectItem>
              {ALL_EVENT_TYPES.map((t) => (
                <SelectItem key={t} value={t}>
                  {EVENT_LABELS[t]}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={folderKindFilter} onValueChange={setFolderKindFilter}>
            <SelectTrigger className="h-9 w-[180px] text-xs">
              <SelectValue placeholder="Folder" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All folders</SelectItem>
              {ALL_FOLDER_KINDS.map((k) => (
                <SelectItem key={k} value={k}>
                  {FOLDER_LABELS[k]}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={actorTypeFilter} onValueChange={setActorTypeFilter}>
            <SelectTrigger className="h-9 w-[140px] text-xs">
              <SelectValue placeholder="Actor" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All actors</SelectItem>
              {ALL_ACTOR_TYPES.map((a) => (
                <SelectItem key={a} value={a}>
                  {ACTOR_LABELS[a]}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
          {hasFilters && (
            <Button
              variant="ghost"
              size="sm"
              onClick={() => {
                setEventTypeFilter("all");
                setFolderKindFilter("all");
                setActorTypeFilter("all");
                setSearch("");
              }}
              className="h-9 px-2 text-xs"
            >
              Clear
            </Button>
          )}
        </div>

        {/* Event list */}
        {isLoading ? (
          <div className="space-y-2">
            {[...Array(5)].map((_, i) => (
              <div
                key={i}
                className="h-12 rounded bg-muted/40 animate-pulse"
              />
            ))}
          </div>
        ) : filtered.length === 0 ? (
          <div className="text-xs text-muted-foreground italic py-6 text-center">
            {hasFilters
              ? "No events match the current filters."
              : "No activity yet. File events will appear here in real time."}
          </div>
        ) : (
          <ul className="divide-y divide-border rounded border">
            {filtered.map((e) => {
              const Icon = ACTOR_ICONS[e.actor_type] || Activity;
              const ts = e.created_at ? new Date(e.created_at) : null;
              const meta = (e.metadata && typeof e.metadata === "object") ? e.metadata : null;
              return (
                <li key={e.id} className="px-3 py-2 hover:bg-muted/40 text-xs flex items-start gap-3">
                  <Icon className="h-4 w-4 text-muted-foreground shrink-0 mt-0.5" />
                  <div className="flex-1 min-w-0">
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge variant={EVENT_TONES[e.event_type] || "secondary"} className="text-[10px]">
                        {EVENT_LABELS[e.event_type] || e.event_type}
                      </Badge>
                      <span className="text-muted-foreground">
                        in <span className="font-medium text-foreground">{FOLDER_LABELS[e.folder_kind] || e.folder_kind}</span>
                      </span>
                      {e.file_name && (
                        <span className="font-mono text-foreground truncate max-w-[280px]" title={e.file_name}>
                          {e.file_name}
                        </span>
                      )}
                      {typeof e.file_size_bytes === "number" && formatBytes(e.file_size_bytes) && (
                        <span className="text-muted-foreground">({formatBytes(e.file_size_bytes)})</span>
                      )}
                    </div>
                    <div className="text-muted-foreground mt-0.5 flex items-center gap-2 flex-wrap">
                      <span title={ts ? format(ts, "PPpp") : ""}>
                        {ts ? formatDistanceToNow(ts, { addSuffix: true }) : "unknown time"}
                      </span>
                      <span>·</span>
                      <span>{ACTOR_LABELS[e.actor_type] || e.actor_type}</span>
                      {meta && Object.keys(meta).length > 0 && (
                        <>
                          <span>·</span>
                          <details className="inline">
                            <summary className="cursor-pointer hover:text-foreground">
                              metadata
                            </summary>
                            <pre className="mt-1 p-2 bg-muted/50 rounded text-[10px] overflow-x-auto whitespace-pre-wrap">
                              {JSON.stringify(meta, null, 2)}
                            </pre>
                          </details>
                        </>
                      )}
                    </div>
                  </div>
                </li>
              );
            })}
          </ul>
        )}

        {/* Pagination */}
        {!isLoading && events && events.length > 0 && (
          <div className="flex items-center justify-between text-xs text-muted-foreground pt-1">
            <span>
              Showing {filtered.length}
              {hasFilters && ` of ${events.length}`} event{filtered.length === 1 ? "" : "s"}
              {!reachedPageEnd && " (paginated)"}
            </span>
            {!reachedPageEnd && (
              <Button
                variant="outline"
                size="sm"
                onClick={() => setPageSize((s) => s + PAGE_INCREMENT)}
                disabled={isFetching}
                className="h-7 text-xs"
              >
                Load more
              </Button>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
